// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		GeoCountry:   newGeoCountry(db, opts...),
		GeoPhoneCode: newGeoPhoneCode(db, opts...),
		GeoRegion:    newGeoRegion(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	GeoCountry   geoCountry
	GeoPhoneCode geoPhoneCode
	GeoRegion    geoRegion
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		GeoCountry:   q.GeoCountry.clone(db),
		GeoPhoneCode: q.GeoPhoneCode.clone(db),
		GeoRegion:    q.GeoRegion.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		GeoCountry:   q.GeoCountry.replaceDB(db),
		GeoPhoneCode: q.GeoPhoneCode.replaceDB(db),
		GeoRegion:    q.GeoRegion.replaceDB(db),
	}
}

type queryCtx struct {
	GeoCountry   IGeoCountryDo
	GeoPhoneCode IGeoPhoneCodeDo
	GeoRegion    IGeoRegionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		GeoCountry:   q.GeoCountry.WithContext(ctx),
		GeoPhoneCode: q.GeoPhoneCode.WithContext(ctx),
		GeoRegion:    q.GeoRegion.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
