// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/byteflowing/base/app/geo/dal/model"
)

func newGeoPhoneCode(db *gorm.DB, opts ...gen.DOOption) geoPhoneCode {
	_geoPhoneCode := geoPhoneCode{}

	_geoPhoneCode.geoPhoneCodeDo.UseDB(db, opts...)
	_geoPhoneCode.geoPhoneCodeDo.UseModel(&model.GeoPhoneCode{})

	tableName := _geoPhoneCode.geoPhoneCodeDo.TableName()
	_geoPhoneCode.ALL = field.NewAsterisk(tableName)
	_geoPhoneCode.ID = field.NewInt64(tableName, "id")
	_geoPhoneCode.Name = field.NewString(tableName, "name")
	_geoPhoneCode.PhoneCode = field.NewString(tableName, "phone_code")
	_geoPhoneCode.MultiLang = field.NewString(tableName, "multi_lang")
	_geoPhoneCode.IsActive = field.NewBool(tableName, "is_active")
	_geoPhoneCode.CreatedAt = field.NewTime(tableName, "created_at")
	_geoPhoneCode.UpdatedAt = field.NewTime(tableName, "updated_at")
	_geoPhoneCode.DeletedAt = field.NewField(tableName, "deleted_at")

	_geoPhoneCode.fillFieldMap()

	return _geoPhoneCode
}

type geoPhoneCode struct {
	geoPhoneCodeDo geoPhoneCodeDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	PhoneCode field.String
	MultiLang field.String
	IsActive  field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (g geoPhoneCode) Table(newTableName string) *geoPhoneCode {
	g.geoPhoneCodeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g geoPhoneCode) As(alias string) *geoPhoneCode {
	g.geoPhoneCodeDo.DO = *(g.geoPhoneCodeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *geoPhoneCode) updateTableName(table string) *geoPhoneCode {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Name = field.NewString(table, "name")
	g.PhoneCode = field.NewString(table, "phone_code")
	g.MultiLang = field.NewString(table, "multi_lang")
	g.IsActive = field.NewBool(table, "is_active")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *geoPhoneCode) WithContext(ctx context.Context) IGeoPhoneCodeDo {
	return g.geoPhoneCodeDo.WithContext(ctx)
}

func (g geoPhoneCode) TableName() string { return g.geoPhoneCodeDo.TableName() }

func (g geoPhoneCode) Alias() string { return g.geoPhoneCodeDo.Alias() }

func (g geoPhoneCode) Columns(cols ...field.Expr) gen.Columns {
	return g.geoPhoneCodeDo.Columns(cols...)
}

func (g *geoPhoneCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *geoPhoneCode) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["phone_code"] = g.PhoneCode
	g.fieldMap["multi_lang"] = g.MultiLang
	g.fieldMap["is_active"] = g.IsActive
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g geoPhoneCode) clone(db *gorm.DB) geoPhoneCode {
	g.geoPhoneCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g geoPhoneCode) replaceDB(db *gorm.DB) geoPhoneCode {
	g.geoPhoneCodeDo.ReplaceDB(db)
	return g
}

type geoPhoneCodeDo struct{ gen.DO }

type IGeoPhoneCodeDo interface {
	gen.SubQuery
	Debug() IGeoPhoneCodeDo
	WithContext(ctx context.Context) IGeoPhoneCodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGeoPhoneCodeDo
	WriteDB() IGeoPhoneCodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGeoPhoneCodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGeoPhoneCodeDo
	Not(conds ...gen.Condition) IGeoPhoneCodeDo
	Or(conds ...gen.Condition) IGeoPhoneCodeDo
	Select(conds ...field.Expr) IGeoPhoneCodeDo
	Where(conds ...gen.Condition) IGeoPhoneCodeDo
	Order(conds ...field.Expr) IGeoPhoneCodeDo
	Distinct(cols ...field.Expr) IGeoPhoneCodeDo
	Omit(cols ...field.Expr) IGeoPhoneCodeDo
	Join(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo
	Group(cols ...field.Expr) IGeoPhoneCodeDo
	Having(conds ...gen.Condition) IGeoPhoneCodeDo
	Limit(limit int) IGeoPhoneCodeDo
	Offset(offset int) IGeoPhoneCodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGeoPhoneCodeDo
	Unscoped() IGeoPhoneCodeDo
	Create(values ...*model.GeoPhoneCode) error
	CreateInBatches(values []*model.GeoPhoneCode, batchSize int) error
	Save(values ...*model.GeoPhoneCode) error
	First() (*model.GeoPhoneCode, error)
	Take() (*model.GeoPhoneCode, error)
	Last() (*model.GeoPhoneCode, error)
	Find() ([]*model.GeoPhoneCode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeoPhoneCode, err error)
	FindInBatches(result *[]*model.GeoPhoneCode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GeoPhoneCode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGeoPhoneCodeDo
	Assign(attrs ...field.AssignExpr) IGeoPhoneCodeDo
	Joins(fields ...field.RelationField) IGeoPhoneCodeDo
	Preload(fields ...field.RelationField) IGeoPhoneCodeDo
	FirstOrInit() (*model.GeoPhoneCode, error)
	FirstOrCreate() (*model.GeoPhoneCode, error)
	FindByPage(offset int, limit int) (result []*model.GeoPhoneCode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGeoPhoneCodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g geoPhoneCodeDo) Debug() IGeoPhoneCodeDo {
	return g.withDO(g.DO.Debug())
}

func (g geoPhoneCodeDo) WithContext(ctx context.Context) IGeoPhoneCodeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g geoPhoneCodeDo) ReadDB() IGeoPhoneCodeDo {
	return g.Clauses(dbresolver.Read)
}

func (g geoPhoneCodeDo) WriteDB() IGeoPhoneCodeDo {
	return g.Clauses(dbresolver.Write)
}

func (g geoPhoneCodeDo) Session(config *gorm.Session) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Session(config))
}

func (g geoPhoneCodeDo) Clauses(conds ...clause.Expression) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g geoPhoneCodeDo) Returning(value interface{}, columns ...string) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g geoPhoneCodeDo) Not(conds ...gen.Condition) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g geoPhoneCodeDo) Or(conds ...gen.Condition) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g geoPhoneCodeDo) Select(conds ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g geoPhoneCodeDo) Where(conds ...gen.Condition) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g geoPhoneCodeDo) Order(conds ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g geoPhoneCodeDo) Distinct(cols ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g geoPhoneCodeDo) Omit(cols ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g geoPhoneCodeDo) Join(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g geoPhoneCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g geoPhoneCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g geoPhoneCodeDo) Group(cols ...field.Expr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g geoPhoneCodeDo) Having(conds ...gen.Condition) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g geoPhoneCodeDo) Limit(limit int) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g geoPhoneCodeDo) Offset(offset int) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g geoPhoneCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g geoPhoneCodeDo) Unscoped() IGeoPhoneCodeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g geoPhoneCodeDo) Create(values ...*model.GeoPhoneCode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g geoPhoneCodeDo) CreateInBatches(values []*model.GeoPhoneCode, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g geoPhoneCodeDo) Save(values ...*model.GeoPhoneCode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g geoPhoneCodeDo) First() (*model.GeoPhoneCode, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoPhoneCode), nil
	}
}

func (g geoPhoneCodeDo) Take() (*model.GeoPhoneCode, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoPhoneCode), nil
	}
}

func (g geoPhoneCodeDo) Last() (*model.GeoPhoneCode, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoPhoneCode), nil
	}
}

func (g geoPhoneCodeDo) Find() ([]*model.GeoPhoneCode, error) {
	result, err := g.DO.Find()
	return result.([]*model.GeoPhoneCode), err
}

func (g geoPhoneCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeoPhoneCode, err error) {
	buf := make([]*model.GeoPhoneCode, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g geoPhoneCodeDo) FindInBatches(result *[]*model.GeoPhoneCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g geoPhoneCodeDo) Attrs(attrs ...field.AssignExpr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g geoPhoneCodeDo) Assign(attrs ...field.AssignExpr) IGeoPhoneCodeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g geoPhoneCodeDo) Joins(fields ...field.RelationField) IGeoPhoneCodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g geoPhoneCodeDo) Preload(fields ...field.RelationField) IGeoPhoneCodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g geoPhoneCodeDo) FirstOrInit() (*model.GeoPhoneCode, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoPhoneCode), nil
	}
}

func (g geoPhoneCodeDo) FirstOrCreate() (*model.GeoPhoneCode, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoPhoneCode), nil
	}
}

func (g geoPhoneCodeDo) FindByPage(offset int, limit int) (result []*model.GeoPhoneCode, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g geoPhoneCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g geoPhoneCodeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g geoPhoneCodeDo) Delete(models ...*model.GeoPhoneCode) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *geoPhoneCodeDo) withDO(do gen.Dao) *geoPhoneCodeDo {
	g.DO = *do.(*gen.DO)
	return g
}
