// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/byteflowing/base/app/geo/dal/model"
)

func newGeoRegion(db *gorm.DB, opts ...gen.DOOption) geoRegion {
	_geoRegion := geoRegion{}

	_geoRegion.geoRegionDo.UseDB(db, opts...)
	_geoRegion.geoRegionDo.UseModel(&model.GeoRegion{})

	tableName := _geoRegion.geoRegionDo.TableName()
	_geoRegion.ALL = field.NewAsterisk(tableName)
	_geoRegion.ID = field.NewInt64(tableName, "id")
	_geoRegion.CountryCca2 = field.NewString(tableName, "country_cca2")
	_geoRegion.Source = field.NewInt16(tableName, "source")
	_geoRegion.ParentCode = field.NewString(tableName, "parent_code")
	_geoRegion.Code = field.NewString(tableName, "code")
	_geoRegion.Level = field.NewInt16(tableName, "level")
	_geoRegion.MultiLang = field.NewString(tableName, "multi_lang")
	_geoRegion.IsActive = field.NewBool(tableName, "is_active")
	_geoRegion.CreatedAt = field.NewTime(tableName, "created_at")
	_geoRegion.UpdatedAt = field.NewTime(tableName, "updated_at")
	_geoRegion.DeletedAt = field.NewField(tableName, "deleted_at")

	_geoRegion.fillFieldMap()

	return _geoRegion
}

type geoRegion struct {
	geoRegionDo geoRegionDo

	ALL         field.Asterisk
	ID          field.Int64
	CountryCca2 field.String
	Source      field.Int16
	ParentCode  field.String
	Code        field.String
	Level       field.Int16
	MultiLang   field.String
	IsActive    field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (g geoRegion) Table(newTableName string) *geoRegion {
	g.geoRegionDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g geoRegion) As(alias string) *geoRegion {
	g.geoRegionDo.DO = *(g.geoRegionDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *geoRegion) updateTableName(table string) *geoRegion {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.CountryCca2 = field.NewString(table, "country_cca2")
	g.Source = field.NewInt16(table, "source")
	g.ParentCode = field.NewString(table, "parent_code")
	g.Code = field.NewString(table, "code")
	g.Level = field.NewInt16(table, "level")
	g.MultiLang = field.NewString(table, "multi_lang")
	g.IsActive = field.NewBool(table, "is_active")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *geoRegion) WithContext(ctx context.Context) IGeoRegionDo {
	return g.geoRegionDo.WithContext(ctx)
}

func (g geoRegion) TableName() string { return g.geoRegionDo.TableName() }

func (g geoRegion) Alias() string { return g.geoRegionDo.Alias() }

func (g geoRegion) Columns(cols ...field.Expr) gen.Columns { return g.geoRegionDo.Columns(cols...) }

func (g *geoRegion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *geoRegion) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 11)
	g.fieldMap["id"] = g.ID
	g.fieldMap["country_cca2"] = g.CountryCca2
	g.fieldMap["source"] = g.Source
	g.fieldMap["parent_code"] = g.ParentCode
	g.fieldMap["code"] = g.Code
	g.fieldMap["level"] = g.Level
	g.fieldMap["multi_lang"] = g.MultiLang
	g.fieldMap["is_active"] = g.IsActive
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g geoRegion) clone(db *gorm.DB) geoRegion {
	g.geoRegionDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g geoRegion) replaceDB(db *gorm.DB) geoRegion {
	g.geoRegionDo.ReplaceDB(db)
	return g
}

type geoRegionDo struct{ gen.DO }

type IGeoRegionDo interface {
	gen.SubQuery
	Debug() IGeoRegionDo
	WithContext(ctx context.Context) IGeoRegionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGeoRegionDo
	WriteDB() IGeoRegionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGeoRegionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGeoRegionDo
	Not(conds ...gen.Condition) IGeoRegionDo
	Or(conds ...gen.Condition) IGeoRegionDo
	Select(conds ...field.Expr) IGeoRegionDo
	Where(conds ...gen.Condition) IGeoRegionDo
	Order(conds ...field.Expr) IGeoRegionDo
	Distinct(cols ...field.Expr) IGeoRegionDo
	Omit(cols ...field.Expr) IGeoRegionDo
	Join(table schema.Tabler, on ...field.Expr) IGeoRegionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGeoRegionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGeoRegionDo
	Group(cols ...field.Expr) IGeoRegionDo
	Having(conds ...gen.Condition) IGeoRegionDo
	Limit(limit int) IGeoRegionDo
	Offset(offset int) IGeoRegionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGeoRegionDo
	Unscoped() IGeoRegionDo
	Create(values ...*model.GeoRegion) error
	CreateInBatches(values []*model.GeoRegion, batchSize int) error
	Save(values ...*model.GeoRegion) error
	First() (*model.GeoRegion, error)
	Take() (*model.GeoRegion, error)
	Last() (*model.GeoRegion, error)
	Find() ([]*model.GeoRegion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeoRegion, err error)
	FindInBatches(result *[]*model.GeoRegion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GeoRegion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGeoRegionDo
	Assign(attrs ...field.AssignExpr) IGeoRegionDo
	Joins(fields ...field.RelationField) IGeoRegionDo
	Preload(fields ...field.RelationField) IGeoRegionDo
	FirstOrInit() (*model.GeoRegion, error)
	FirstOrCreate() (*model.GeoRegion, error)
	FindByPage(offset int, limit int) (result []*model.GeoRegion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGeoRegionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g geoRegionDo) Debug() IGeoRegionDo {
	return g.withDO(g.DO.Debug())
}

func (g geoRegionDo) WithContext(ctx context.Context) IGeoRegionDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g geoRegionDo) ReadDB() IGeoRegionDo {
	return g.Clauses(dbresolver.Read)
}

func (g geoRegionDo) WriteDB() IGeoRegionDo {
	return g.Clauses(dbresolver.Write)
}

func (g geoRegionDo) Session(config *gorm.Session) IGeoRegionDo {
	return g.withDO(g.DO.Session(config))
}

func (g geoRegionDo) Clauses(conds ...clause.Expression) IGeoRegionDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g geoRegionDo) Returning(value interface{}, columns ...string) IGeoRegionDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g geoRegionDo) Not(conds ...gen.Condition) IGeoRegionDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g geoRegionDo) Or(conds ...gen.Condition) IGeoRegionDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g geoRegionDo) Select(conds ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g geoRegionDo) Where(conds ...gen.Condition) IGeoRegionDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g geoRegionDo) Order(conds ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g geoRegionDo) Distinct(cols ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g geoRegionDo) Omit(cols ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g geoRegionDo) Join(table schema.Tabler, on ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g geoRegionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g geoRegionDo) RightJoin(table schema.Tabler, on ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g geoRegionDo) Group(cols ...field.Expr) IGeoRegionDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g geoRegionDo) Having(conds ...gen.Condition) IGeoRegionDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g geoRegionDo) Limit(limit int) IGeoRegionDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g geoRegionDo) Offset(offset int) IGeoRegionDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g geoRegionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGeoRegionDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g geoRegionDo) Unscoped() IGeoRegionDo {
	return g.withDO(g.DO.Unscoped())
}

func (g geoRegionDo) Create(values ...*model.GeoRegion) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g geoRegionDo) CreateInBatches(values []*model.GeoRegion, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g geoRegionDo) Save(values ...*model.GeoRegion) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g geoRegionDo) First() (*model.GeoRegion, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoRegion), nil
	}
}

func (g geoRegionDo) Take() (*model.GeoRegion, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoRegion), nil
	}
}

func (g geoRegionDo) Last() (*model.GeoRegion, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoRegion), nil
	}
}

func (g geoRegionDo) Find() ([]*model.GeoRegion, error) {
	result, err := g.DO.Find()
	return result.([]*model.GeoRegion), err
}

func (g geoRegionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeoRegion, err error) {
	buf := make([]*model.GeoRegion, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g geoRegionDo) FindInBatches(result *[]*model.GeoRegion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g geoRegionDo) Attrs(attrs ...field.AssignExpr) IGeoRegionDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g geoRegionDo) Assign(attrs ...field.AssignExpr) IGeoRegionDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g geoRegionDo) Joins(fields ...field.RelationField) IGeoRegionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g geoRegionDo) Preload(fields ...field.RelationField) IGeoRegionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g geoRegionDo) FirstOrInit() (*model.GeoRegion, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoRegion), nil
	}
}

func (g geoRegionDo) FirstOrCreate() (*model.GeoRegion, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeoRegion), nil
	}
}

func (g geoRegionDo) FindByPage(offset int, limit int) (result []*model.GeoRegion, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g geoRegionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g geoRegionDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g geoRegionDo) Delete(models ...*model.GeoRegion) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *geoRegionDo) withDO(do gen.Dao) *geoRegionDo {
	g.DO = *do.(*gen.DO)
	return g
}
