// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserSignLog = "user_sign_log"

// UserSignLog mapped from table <user_sign_log>
type UserSignLog struct {
	ID               int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID         string         `gorm:"column:tenant_id;type:character varying(50);not null;index:idx_user_sign_log_uni_uid_created_at,priority:2" json:"tenant_id"`
	UID              int64          `gorm:"column:uid;type:bigint;not null;index:idx_user_sign_log_uni_uid_created_at,priority:3" json:"uid"`
	Type             int16          `gorm:"column:type;type:smallint;not null" json:"type"`
	Status           int16          `gorm:"column:status;type:smallint;not null" json:"status"`
	Identifier       string         `gorm:"column:identifier;type:character varying(50);not null" json:"identifier"`
	IP               *string        `gorm:"column:ip;type:character varying(50)" json:"ip"`
	Location         *string        `gorm:"column:location;type:character varying(100)" json:"location"`
	Agent            *string        `gorm:"column:agent;type:character varying(255)" json:"agent"`
	Device           *string        `gorm:"column:device;type:character varying(255)" json:"device"`
	AccessJti        string         `gorm:"column:access_jti;type:character varying(64);not null;uniqueIndex:idx_user_sign_log_access_token_id,priority:1" json:"access_jti"`
	RefreshJti       string         `gorm:"column:refresh_jti;type:character varying(64);not null;uniqueIndex:idx_user_sign_log_refresh_token_id,priority:1" json:"refresh_jti"`
	AccessExpiredAt  *time.Time     `gorm:"column:access_expired_at;type:timestamp with time zone" json:"access_expired_at"`
	RefreshExpiredAt *time.Time     `gorm:"column:refresh_expired_at;type:timestamp with time zone" json:"refresh_expired_at"`
	UpdatedAt        *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	CreatedAt        *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_user_sign_log_uni_uid_created_at,priority:1;default:now()" json:"created_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName UserSignLog's table name
func (*UserSignLog) TableName() string {
	return TableNameUserSignLog
}
