// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserAccount = "user_account"

// UserAccount mapped from table <user_account>
type UserAccount struct {
	ID                int64          `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	TenantID          string         `gorm:"column:tenant_id;type:character varying(50);not null;uniqueIndex:idx_user_account_email,priority:2;uniqueIndex:idx_user_account_number,priority:2;uniqueIndex:idx_user_account_phone,priority:3" json:"tenant_id"`
	Number            string         `gorm:"column:number;type:character varying(50);not null;uniqueIndex:idx_user_account_number,priority:1" json:"number"`
	Name              *string        `gorm:"column:name;type:character varying(50)" json:"name"`
	Alias_            *string        `gorm:"column:alias;type:character varying(50)" json:"alias"`
	Password          *string        `gorm:"column:password;type:character varying(100)" json:"password"`
	Avatar            *string        `gorm:"column:avatar;type:character varying(255)" json:"avatar"`
	Gender            *int16         `gorm:"column:gender;type:smallint" json:"gender"`
	Birthday          *time.Time     `gorm:"column:birthday;type:date" json:"birthday"`
	PhoneCountryCode  string         `gorm:"column:phone_country_code;type:character varying(10);not null;uniqueIndex:idx_user_account_phone,priority:2" json:"phone_country_code"`
	Phone             string         `gorm:"column:phone;type:character varying(20);not null;uniqueIndex:idx_user_account_phone,priority:1" json:"phone"`
	Email             string         `gorm:"column:email;type:character varying(100);not null;uniqueIndex:idx_user_account_email,priority:1" json:"email"`
	CountryCode       string         `gorm:"column:country_code;type:character varying(20);not null;index:idx_user_account_region,priority:2" json:"country_code"`
	ProvinceCode      string         `gorm:"column:province_code;type:character varying(20);not null;index:idx_user_account_region,priority:4" json:"province_code"`
	CityCode          string         `gorm:"column:city_code;type:character varying(20);not null;index:idx_user_account_region,priority:1" json:"city_code"`
	DistrictCode      string         `gorm:"column:district_code;type:character varying(20);not null;index:idx_user_account_region,priority:3" json:"district_code"`
	Addr              *string        `gorm:"column:addr;type:character varying(255)" json:"addr"`
	Status            int16          `gorm:"column:status;type:smallint;not null" json:"status"`
	Source            int16          `gorm:"column:source;type:smallint;not null" json:"source"`
	SignupType        int16          `gorm:"column:signup_type;type:smallint;not null" json:"signup_type"`
	PhoneVerified     bool           `gorm:"column:phone_verified;type:boolean;not null" json:"phone_verified"`
	EmailVerified     bool           `gorm:"column:email_verified;type:boolean;not null" json:"email_verified"`
	Type              *int16         `gorm:"column:type;type:smallint" json:"type"`
	Level             *int32         `gorm:"column:level;type:integer" json:"level"`
	RegisterIP        *string        `gorm:"column:register_ip;type:character varying(50)" json:"register_ip"`
	RegisterDevice    *string        `gorm:"column:register_device;type:character varying(255)" json:"register_device"`
	RegisterAgent     *string        `gorm:"column:register_agent;type:character varying(255)" json:"register_agent"`
	RegisterLocation  *string        `gorm:"column:register_location;type:character varying(50)" json:"register_location"`
	UpdatedAt         *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	CreatedAt         *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	PasswordUpdatedAt *time.Time     `gorm:"column:password_updated_at;type:timestamp with time zone" json:"password_updated_at"`
	Ext               *string        `gorm:"column:ext;type:json" json:"ext"`
}

// TableName UserAccount's table name
func (*UserAccount) TableName() string {
	return TableNameUserAccount
}
