// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserAuth = "user_auth"

// UserAuth mapped from table <user_auth>
type UserAuth struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TenantID  string         `gorm:"column:tenant_id;type:character varying(50);not null;index:idx_user_auth_tenant_id,priority:1" json:"tenant_id"`
	UID       int64          `gorm:"column:uid;type:bigint;not null;index:idx_user_auth_uid,priority:1" json:"uid"`
	Type      int16          `gorm:"column:type;type:smallint;not null" json:"type"`
	Status    int16          `gorm:"column:status;type:smallint;not null" json:"status"`
	Appid     string         `gorm:"column:appid;type:character varying(100);not null;index:idx_user_auth_app_id,priority:1" json:"appid"`
	OpenID    string         `gorm:"column:open_id;type:character varying(100);not null;uniqueIndex:idx_uni_user_auth_open_id,priority:1" json:"open_id"`
	UnionID   string         `gorm:"column:union_id;type:character varying(100);not null;index:idx_user_auth_union_id,priority:1" json:"union_id"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
