// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserAuth = "user_auth"

// UserAuth mapped from table <user_auth>
type UserAuth struct {
	ID         int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UID        int64   `gorm:"column:uid;type:bigint;not null;index:idx_auth_uid,priority:1" json:"uid"`
	Type       int16   `gorm:"column:type;type:smallint;not null" json:"type"`
	Status     int16   `gorm:"column:status;type:smallint;not null" json:"status"`
	Identifier string  `gorm:"column:identifier;type:character varying(100);not null;index:idx_auth_identifier,priority:1" json:"identifier"`
	Credential string  `gorm:"column:credential;type:character varying(128);not null" json:"credential"`
	UnionID    *string `gorm:"column:union_id;type:character varying(100)" json:"union_id"`
	DeletedAt  *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	UpdatedAt  int64   `gorm:"column:updated_at;type:bigint;not null" json:"updated_at"`
	CreatedAt  int64   `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
