// Code generated by Kitex v0.14.1. DO NOT EDIT.

package base

import "context"

type BaseService interface {
	SendCaptcha(ctx context.Context, req *SendCaptchaReq) (res *SendCaptchaResp, err error)
	VerifyCaptcha(ctx context.Context, req *VerifyCaptchaReq) (res *VerifyCaptchaResp, err error)
	PagingGetSmsMessages(ctx context.Context, req *PagingGetSmsMessagesReq) (res *PagingGetSmsMessagesResp, err error)
	SendPhoneCaptcha(ctx context.Context, req *SendPhoneCaptchaReq) (res *SendPhoneCaptchaResp, err error)
	SendEmailCaptcha(ctx context.Context, req *SendEmailCaptchaReq) (res *SendEmailCaptchaResp, err error)
	Login(ctx context.Context, req *LoginReq) (res *LoginResp, err error)
	Logout(ctx context.Context, req *LogoutReq) (res *LogoutResp, err error)
	ForceLogoutBySessionId(ctx context.Context, req *ForceLogoutBySessionIdReq) (res *ForceLogoutBySessionIdResp, err error)
	RefreshToken(ctx context.Context, req *RefreshTokenReq) (res *RefreshTokenResp, err error)
	VerifyToken(ctx context.Context, req *VerifyTokenReq) (res *VerifyTokenResp, err error)
	AddUser(ctx context.Context, req *AddUserReq) (res *AddUserResp, err error)
	BatchAddUsers(ctx context.Context, req *BatchAddUsersReq) (res *BatchAddUsersResp, err error)
	UpdateUser(ctx context.Context, req *UpdateUserReq) (res *UpdateUserResp, err error)
	DeleteUser(ctx context.Context, req *DeleteUserReq) (res *DeleteUserResp, err error)
	BatchDeleteUsers(ctx context.Context, req *BatchDeleteUsersReq) (res *BatchDeleteUsersResp, err error)
	GetUserByNumber(ctx context.Context, req *GetUserByNumberReq) (res *GetUserByNumberResp, err error)
	PagingGetUsers(ctx context.Context, req *PagingGetUsersReq) (res *PagingGetUsersResp, err error)
	GetUserLoginLogs(ctx context.Context, req *GetUserLoginLogsReq) (res *GetUserLoginLogsResp, err error)
	PagingGetLoginLogs(ctx context.Context, req *PagingGetLoginLogsReq) (res *PagingGetLoginLogsResp, err error)
}
