// Code generated by Kitex v0.14.1. DO NOT EDIT.

package base

import "github.com/cloudwego/prutal"

type CommonResp struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
}

func (x *CommonResp) Reset() { *x = CommonResp{} }

func (x *CommonResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommonResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonResp) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Agent struct {
	Ip       *string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`             // ip地址
	Location *string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"` // 坐标
	Device   *string `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`     // 设备信息
	Agent    *string `protobuf:"bytes,4,opt,name=agent" json:"agent,omitempty"`       // 软件信息
}

func (x *Agent) Reset() { *x = Agent{} }

func (x *Agent) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Agent) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Agent) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Agent) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *Agent) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *Agent) GetAgent() string {
	if x != nil && x.Agent != nil {
		return *x.Agent
	}
	return ""
}
