// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMapInterfaceCount = "map_interface_count"

// MapInterfaceCount mapped from table <map_interface_count>
type MapInterfaceCount struct {
	ID            int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MapID         int64          `gorm:"column:map_id;type:bigint;not null;uniqueIndex:map_interface_count_unique_count_interface_type,priority:2" json:"map_id"`
	InterfaceType int32          `gorm:"column:interface_type;type:integer;not null;uniqueIndex:map_interface_count_unique_count_interface_type,priority:1" json:"interface_type"`
	Day           *time.Time     `gorm:"column:day;type:date;not null;index:map_interface_count_day,priority:1;default:now()" json:"day"`
	Count         int32          `gorm:"column:count;type:integer;not null" json:"count"`
	ErrCount      int32          `gorm:"column:err_count;type:integer;not null" json:"err_count"`
	CreatedAt     *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:map_interface_count_created_at,priority:1;default:now()" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName MapInterfaceCount's table name
func (*MapInterfaceCount) TableName() string {
	return TableNameMapInterfaceCount
}
