// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMapInterface = "map_interface"

// MapInterface mapped from table <map_interface>
type MapInterface struct {
	ID            int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MapID         int64          `gorm:"column:map_id;type:bigint;not null;uniqueIndex:map_interface_unique_map_id_interface_type,priority:2" json:"map_id"`
	InterfaceType int32          `gorm:"column:interface_type;type:integer;not null;uniqueIndex:map_interface_unique_map_id_interface_type,priority:1" json:"interface_type"`
	SecondLimit   *int32         `gorm:"column:second_limit;type:integer" json:"second_limit"`
	DailyLimit    *int32         `gorm:"column:daily_limit;type:integer" json:"daily_limit"`
	CreatedAt     *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName MapInterface's table name
func (*MapInterface) TableName() string {
	return TableNameMapInterface
}
