// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMapAccount = "map_account"

// MapAccount mapped from table <map_account>
type MapAccount struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;type:character varying(100);not null;uniqueIndex:map_account_object_name,priority:1" json:"name"`
	MapSource int16          `gorm:"column:map_source;type:smallint;not null" json:"map_source"`
	MapType   int16          `gorm:"column:map_type;type:smallint;not null" json:"map_type"`
	Key       string         `gorm:"column:key;type:character varying(100);not null" json:"key"`
	Status    int16          `gorm:"column:status;type:smallint;not null;index:map_account_uni_created_status,priority:2" json:"status"`
	OwnerType int16          `gorm:"column:owner_type;type:smallint;not null" json:"owner_type"`
	ObjectID  int64          `gorm:"column:object_id;type:bigint;not null;uniqueIndex:map_account_object_name,priority:2" json:"object_id"`
	Comment   *string        `gorm:"column:comment;type:character varying(255)" json:"comment"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:map_account_uni_created_status,priority:1;default:now()" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName MapAccount's table name
func (*MapAccount) TableName() string {
	return TableNameMapAccount
}
