// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package message

import (
	"github.com/byteflowing/base/app/message/service"
	"github.com/byteflowing/base/singleton"
	"github.com/byteflowing/proto/gen/go/config/v1"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewMessageServiceWithConfig(cfg *configv1.Config) *service.MessageService {
	redisConfig := cfg.Redis
	redis := singleton.NewRDB(redisConfig)
	serviceMessageService := service.NewMessageService(cfg, redis)
	return serviceMessageService
}

// wire.go:

var providerSet = wire.NewSet(singleton.NewRDB, service.NewMessageService, wire.FieldsOf(new(*configv1.Config), "Redis"))
