// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		MapAccount:        newMapAccount(db, opts...),
		MapInterface:      newMapInterface(db, opts...),
		MapInterfaceCount: newMapInterfaceCount(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	MapAccount        mapAccount
	MapInterface      mapInterface
	MapInterfaceCount mapInterfaceCount
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		MapAccount:        q.MapAccount.clone(db),
		MapInterface:      q.MapInterface.clone(db),
		MapInterfaceCount: q.MapInterfaceCount.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		MapAccount:        q.MapAccount.replaceDB(db),
		MapInterface:      q.MapInterface.replaceDB(db),
		MapInterfaceCount: q.MapInterfaceCount.replaceDB(db),
	}
}

type queryCtx struct {
	MapAccount        IMapAccountDo
	MapInterface      IMapInterfaceDo
	MapInterfaceCount IMapInterfaceCountDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		MapAccount:        q.MapAccount.WithContext(ctx),
		MapInterface:      q.MapInterface.WithContext(ctx),
		MapInterfaceCount: q.MapInterfaceCount.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
