// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/byteflowing/base/app/maps/dal/model"
)

func newMapAccount(db *gorm.DB, opts ...gen.DOOption) mapAccount {
	_mapAccount := mapAccount{}

	_mapAccount.mapAccountDo.UseDB(db, opts...)
	_mapAccount.mapAccountDo.UseModel(&model.MapAccount{})

	tableName := _mapAccount.mapAccountDo.TableName()
	_mapAccount.ALL = field.NewAsterisk(tableName)
	_mapAccount.ID = field.NewInt64(tableName, "id")
	_mapAccount.Name = field.NewString(tableName, "name")
	_mapAccount.MapSource = field.NewInt16(tableName, "map_source")
	_mapAccount.MapType = field.NewInt16(tableName, "map_type")
	_mapAccount.Key = field.NewString(tableName, "key")
	_mapAccount.Status = field.NewInt16(tableName, "status")
	_mapAccount.OwnerType = field.NewInt16(tableName, "owner_type")
	_mapAccount.ObjectID = field.NewInt64(tableName, "object_id")
	_mapAccount.Comment = field.NewString(tableName, "comment")
	_mapAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_mapAccount.UpdatedAt = field.NewTime(tableName, "updated_at")
	_mapAccount.DeletedAt = field.NewField(tableName, "deleted_at")

	_mapAccount.fillFieldMap()

	return _mapAccount
}

type mapAccount struct {
	mapAccountDo mapAccountDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	MapSource field.Int16
	MapType   field.Int16
	Key       field.String
	Status    field.Int16
	OwnerType field.Int16
	ObjectID  field.Int64
	Comment   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (m mapAccount) Table(newTableName string) *mapAccount {
	m.mapAccountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mapAccount) As(alias string) *mapAccount {
	m.mapAccountDo.DO = *(m.mapAccountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mapAccount) updateTableName(table string) *mapAccount {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Name = field.NewString(table, "name")
	m.MapSource = field.NewInt16(table, "map_source")
	m.MapType = field.NewInt16(table, "map_type")
	m.Key = field.NewString(table, "key")
	m.Status = field.NewInt16(table, "status")
	m.OwnerType = field.NewInt16(table, "owner_type")
	m.ObjectID = field.NewInt64(table, "object_id")
	m.Comment = field.NewString(table, "comment")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *mapAccount) WithContext(ctx context.Context) IMapAccountDo {
	return m.mapAccountDo.WithContext(ctx)
}

func (m mapAccount) TableName() string { return m.mapAccountDo.TableName() }

func (m mapAccount) Alias() string { return m.mapAccountDo.Alias() }

func (m mapAccount) Columns(cols ...field.Expr) gen.Columns { return m.mapAccountDo.Columns(cols...) }

func (m *mapAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mapAccount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["map_source"] = m.MapSource
	m.fieldMap["map_type"] = m.MapType
	m.fieldMap["key"] = m.Key
	m.fieldMap["status"] = m.Status
	m.fieldMap["owner_type"] = m.OwnerType
	m.fieldMap["object_id"] = m.ObjectID
	m.fieldMap["comment"] = m.Comment
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m mapAccount) clone(db *gorm.DB) mapAccount {
	m.mapAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mapAccount) replaceDB(db *gorm.DB) mapAccount {
	m.mapAccountDo.ReplaceDB(db)
	return m
}

type mapAccountDo struct{ gen.DO }

type IMapAccountDo interface {
	gen.SubQuery
	Debug() IMapAccountDo
	WithContext(ctx context.Context) IMapAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMapAccountDo
	WriteDB() IMapAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMapAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMapAccountDo
	Not(conds ...gen.Condition) IMapAccountDo
	Or(conds ...gen.Condition) IMapAccountDo
	Select(conds ...field.Expr) IMapAccountDo
	Where(conds ...gen.Condition) IMapAccountDo
	Order(conds ...field.Expr) IMapAccountDo
	Distinct(cols ...field.Expr) IMapAccountDo
	Omit(cols ...field.Expr) IMapAccountDo
	Join(table schema.Tabler, on ...field.Expr) IMapAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMapAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMapAccountDo
	Group(cols ...field.Expr) IMapAccountDo
	Having(conds ...gen.Condition) IMapAccountDo
	Limit(limit int) IMapAccountDo
	Offset(offset int) IMapAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMapAccountDo
	Unscoped() IMapAccountDo
	Create(values ...*model.MapAccount) error
	CreateInBatches(values []*model.MapAccount, batchSize int) error
	Save(values ...*model.MapAccount) error
	First() (*model.MapAccount, error)
	Take() (*model.MapAccount, error)
	Last() (*model.MapAccount, error)
	Find() ([]*model.MapAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapAccount, err error)
	FindInBatches(result *[]*model.MapAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MapAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMapAccountDo
	Assign(attrs ...field.AssignExpr) IMapAccountDo
	Joins(fields ...field.RelationField) IMapAccountDo
	Preload(fields ...field.RelationField) IMapAccountDo
	FirstOrInit() (*model.MapAccount, error)
	FirstOrCreate() (*model.MapAccount, error)
	FindByPage(offset int, limit int) (result []*model.MapAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMapAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mapAccountDo) Debug() IMapAccountDo {
	return m.withDO(m.DO.Debug())
}

func (m mapAccountDo) WithContext(ctx context.Context) IMapAccountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mapAccountDo) ReadDB() IMapAccountDo {
	return m.Clauses(dbresolver.Read)
}

func (m mapAccountDo) WriteDB() IMapAccountDo {
	return m.Clauses(dbresolver.Write)
}

func (m mapAccountDo) Session(config *gorm.Session) IMapAccountDo {
	return m.withDO(m.DO.Session(config))
}

func (m mapAccountDo) Clauses(conds ...clause.Expression) IMapAccountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mapAccountDo) Returning(value interface{}, columns ...string) IMapAccountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mapAccountDo) Not(conds ...gen.Condition) IMapAccountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mapAccountDo) Or(conds ...gen.Condition) IMapAccountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mapAccountDo) Select(conds ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mapAccountDo) Where(conds ...gen.Condition) IMapAccountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mapAccountDo) Order(conds ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mapAccountDo) Distinct(cols ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mapAccountDo) Omit(cols ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mapAccountDo) Join(table schema.Tabler, on ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mapAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mapAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mapAccountDo) Group(cols ...field.Expr) IMapAccountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mapAccountDo) Having(conds ...gen.Condition) IMapAccountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mapAccountDo) Limit(limit int) IMapAccountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mapAccountDo) Offset(offset int) IMapAccountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mapAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMapAccountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mapAccountDo) Unscoped() IMapAccountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mapAccountDo) Create(values ...*model.MapAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mapAccountDo) CreateInBatches(values []*model.MapAccount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mapAccountDo) Save(values ...*model.MapAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mapAccountDo) First() (*model.MapAccount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapAccount), nil
	}
}

func (m mapAccountDo) Take() (*model.MapAccount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapAccount), nil
	}
}

func (m mapAccountDo) Last() (*model.MapAccount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapAccount), nil
	}
}

func (m mapAccountDo) Find() ([]*model.MapAccount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MapAccount), err
}

func (m mapAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapAccount, err error) {
	buf := make([]*model.MapAccount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mapAccountDo) FindInBatches(result *[]*model.MapAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mapAccountDo) Attrs(attrs ...field.AssignExpr) IMapAccountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mapAccountDo) Assign(attrs ...field.AssignExpr) IMapAccountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mapAccountDo) Joins(fields ...field.RelationField) IMapAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mapAccountDo) Preload(fields ...field.RelationField) IMapAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mapAccountDo) FirstOrInit() (*model.MapAccount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapAccount), nil
	}
}

func (m mapAccountDo) FirstOrCreate() (*model.MapAccount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapAccount), nil
	}
}

func (m mapAccountDo) FindByPage(offset int, limit int) (result []*model.MapAccount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mapAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mapAccountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mapAccountDo) Delete(models ...*model.MapAccount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mapAccountDo) withDO(do gen.Dao) *mapAccountDo {
	m.DO = *do.(*gen.DO)
	return m
}
