// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/byteflowing/base/app/maps/dal/model"
)

func newMapInterface(db *gorm.DB, opts ...gen.DOOption) mapInterface {
	_mapInterface := mapInterface{}

	_mapInterface.mapInterfaceDo.UseDB(db, opts...)
	_mapInterface.mapInterfaceDo.UseModel(&model.MapInterface{})

	tableName := _mapInterface.mapInterfaceDo.TableName()
	_mapInterface.ALL = field.NewAsterisk(tableName)
	_mapInterface.ID = field.NewInt64(tableName, "id")
	_mapInterface.MapID = field.NewInt64(tableName, "map_id")
	_mapInterface.InterfaceType = field.NewInt32(tableName, "interface_type")
	_mapInterface.SecondLimit = field.NewInt32(tableName, "second_limit")
	_mapInterface.DailyLimit = field.NewInt32(tableName, "daily_limit")
	_mapInterface.CreatedAt = field.NewTime(tableName, "created_at")
	_mapInterface.UpdatedAt = field.NewTime(tableName, "updated_at")
	_mapInterface.DeletedAt = field.NewField(tableName, "deleted_at")

	_mapInterface.fillFieldMap()

	return _mapInterface
}

type mapInterface struct {
	mapInterfaceDo mapInterfaceDo

	ALL           field.Asterisk
	ID            field.Int64
	MapID         field.Int64
	InterfaceType field.Int32
	SecondLimit   field.Int32
	DailyLimit    field.Int32
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field

	fieldMap map[string]field.Expr
}

func (m mapInterface) Table(newTableName string) *mapInterface {
	m.mapInterfaceDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mapInterface) As(alias string) *mapInterface {
	m.mapInterfaceDo.DO = *(m.mapInterfaceDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mapInterface) updateTableName(table string) *mapInterface {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MapID = field.NewInt64(table, "map_id")
	m.InterfaceType = field.NewInt32(table, "interface_type")
	m.SecondLimit = field.NewInt32(table, "second_limit")
	m.DailyLimit = field.NewInt32(table, "daily_limit")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *mapInterface) WithContext(ctx context.Context) IMapInterfaceDo {
	return m.mapInterfaceDo.WithContext(ctx)
}

func (m mapInterface) TableName() string { return m.mapInterfaceDo.TableName() }

func (m mapInterface) Alias() string { return m.mapInterfaceDo.Alias() }

func (m mapInterface) Columns(cols ...field.Expr) gen.Columns {
	return m.mapInterfaceDo.Columns(cols...)
}

func (m *mapInterface) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mapInterface) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["map_id"] = m.MapID
	m.fieldMap["interface_type"] = m.InterfaceType
	m.fieldMap["second_limit"] = m.SecondLimit
	m.fieldMap["daily_limit"] = m.DailyLimit
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m mapInterface) clone(db *gorm.DB) mapInterface {
	m.mapInterfaceDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mapInterface) replaceDB(db *gorm.DB) mapInterface {
	m.mapInterfaceDo.ReplaceDB(db)
	return m
}

type mapInterfaceDo struct{ gen.DO }

type IMapInterfaceDo interface {
	gen.SubQuery
	Debug() IMapInterfaceDo
	WithContext(ctx context.Context) IMapInterfaceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMapInterfaceDo
	WriteDB() IMapInterfaceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMapInterfaceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMapInterfaceDo
	Not(conds ...gen.Condition) IMapInterfaceDo
	Or(conds ...gen.Condition) IMapInterfaceDo
	Select(conds ...field.Expr) IMapInterfaceDo
	Where(conds ...gen.Condition) IMapInterfaceDo
	Order(conds ...field.Expr) IMapInterfaceDo
	Distinct(cols ...field.Expr) IMapInterfaceDo
	Omit(cols ...field.Expr) IMapInterfaceDo
	Join(table schema.Tabler, on ...field.Expr) IMapInterfaceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceDo
	Group(cols ...field.Expr) IMapInterfaceDo
	Having(conds ...gen.Condition) IMapInterfaceDo
	Limit(limit int) IMapInterfaceDo
	Offset(offset int) IMapInterfaceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMapInterfaceDo
	Unscoped() IMapInterfaceDo
	Create(values ...*model.MapInterface) error
	CreateInBatches(values []*model.MapInterface, batchSize int) error
	Save(values ...*model.MapInterface) error
	First() (*model.MapInterface, error)
	Take() (*model.MapInterface, error)
	Last() (*model.MapInterface, error)
	Find() ([]*model.MapInterface, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapInterface, err error)
	FindInBatches(result *[]*model.MapInterface, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MapInterface) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMapInterfaceDo
	Assign(attrs ...field.AssignExpr) IMapInterfaceDo
	Joins(fields ...field.RelationField) IMapInterfaceDo
	Preload(fields ...field.RelationField) IMapInterfaceDo
	FirstOrInit() (*model.MapInterface, error)
	FirstOrCreate() (*model.MapInterface, error)
	FindByPage(offset int, limit int) (result []*model.MapInterface, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMapInterfaceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mapInterfaceDo) Debug() IMapInterfaceDo {
	return m.withDO(m.DO.Debug())
}

func (m mapInterfaceDo) WithContext(ctx context.Context) IMapInterfaceDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mapInterfaceDo) ReadDB() IMapInterfaceDo {
	return m.Clauses(dbresolver.Read)
}

func (m mapInterfaceDo) WriteDB() IMapInterfaceDo {
	return m.Clauses(dbresolver.Write)
}

func (m mapInterfaceDo) Session(config *gorm.Session) IMapInterfaceDo {
	return m.withDO(m.DO.Session(config))
}

func (m mapInterfaceDo) Clauses(conds ...clause.Expression) IMapInterfaceDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mapInterfaceDo) Returning(value interface{}, columns ...string) IMapInterfaceDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mapInterfaceDo) Not(conds ...gen.Condition) IMapInterfaceDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mapInterfaceDo) Or(conds ...gen.Condition) IMapInterfaceDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mapInterfaceDo) Select(conds ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mapInterfaceDo) Where(conds ...gen.Condition) IMapInterfaceDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mapInterfaceDo) Order(conds ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mapInterfaceDo) Distinct(cols ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mapInterfaceDo) Omit(cols ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mapInterfaceDo) Join(table schema.Tabler, on ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mapInterfaceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mapInterfaceDo) RightJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mapInterfaceDo) Group(cols ...field.Expr) IMapInterfaceDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mapInterfaceDo) Having(conds ...gen.Condition) IMapInterfaceDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mapInterfaceDo) Limit(limit int) IMapInterfaceDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mapInterfaceDo) Offset(offset int) IMapInterfaceDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mapInterfaceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMapInterfaceDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mapInterfaceDo) Unscoped() IMapInterfaceDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mapInterfaceDo) Create(values ...*model.MapInterface) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mapInterfaceDo) CreateInBatches(values []*model.MapInterface, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mapInterfaceDo) Save(values ...*model.MapInterface) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mapInterfaceDo) First() (*model.MapInterface, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterface), nil
	}
}

func (m mapInterfaceDo) Take() (*model.MapInterface, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterface), nil
	}
}

func (m mapInterfaceDo) Last() (*model.MapInterface, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterface), nil
	}
}

func (m mapInterfaceDo) Find() ([]*model.MapInterface, error) {
	result, err := m.DO.Find()
	return result.([]*model.MapInterface), err
}

func (m mapInterfaceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapInterface, err error) {
	buf := make([]*model.MapInterface, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mapInterfaceDo) FindInBatches(result *[]*model.MapInterface, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mapInterfaceDo) Attrs(attrs ...field.AssignExpr) IMapInterfaceDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mapInterfaceDo) Assign(attrs ...field.AssignExpr) IMapInterfaceDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mapInterfaceDo) Joins(fields ...field.RelationField) IMapInterfaceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mapInterfaceDo) Preload(fields ...field.RelationField) IMapInterfaceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mapInterfaceDo) FirstOrInit() (*model.MapInterface, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterface), nil
	}
}

func (m mapInterfaceDo) FirstOrCreate() (*model.MapInterface, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterface), nil
	}
}

func (m mapInterfaceDo) FindByPage(offset int, limit int) (result []*model.MapInterface, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mapInterfaceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mapInterfaceDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mapInterfaceDo) Delete(models ...*model.MapInterface) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mapInterfaceDo) withDO(do gen.Dao) *mapInterfaceDo {
	m.DO = *do.(*gen.DO)
	return m
}
