// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/byteflowing/base/app/maps/dal/model"
)

func newMapInterfaceCount(db *gorm.DB, opts ...gen.DOOption) mapInterfaceCount {
	_mapInterfaceCount := mapInterfaceCount{}

	_mapInterfaceCount.mapInterfaceCountDo.UseDB(db, opts...)
	_mapInterfaceCount.mapInterfaceCountDo.UseModel(&model.MapInterfaceCount{})

	tableName := _mapInterfaceCount.mapInterfaceCountDo.TableName()
	_mapInterfaceCount.ALL = field.NewAsterisk(tableName)
	_mapInterfaceCount.ID = field.NewInt64(tableName, "id")
	_mapInterfaceCount.MapID = field.NewInt64(tableName, "map_id")
	_mapInterfaceCount.InterfaceType = field.NewInt32(tableName, "interface_type")
	_mapInterfaceCount.Day = field.NewTime(tableName, "day")
	_mapInterfaceCount.Count = field.NewInt32(tableName, "count")
	_mapInterfaceCount.ErrCount = field.NewInt32(tableName, "err_count")
	_mapInterfaceCount.CreatedAt = field.NewTime(tableName, "created_at")
	_mapInterfaceCount.UpdatedAt = field.NewTime(tableName, "updated_at")
	_mapInterfaceCount.DeletedAt = field.NewField(tableName, "deleted_at")

	_mapInterfaceCount.fillFieldMap()

	return _mapInterfaceCount
}

type mapInterfaceCount struct {
	mapInterfaceCountDo mapInterfaceCountDo

	ALL           field.Asterisk
	ID            field.Int64
	MapID         field.Int64
	InterfaceType field.Int32
	Day           field.Time
	Count         field.Int32
	ErrCount      field.Int32
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field

	fieldMap map[string]field.Expr
}

func (m mapInterfaceCount) Table(newTableName string) *mapInterfaceCount {
	m.mapInterfaceCountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mapInterfaceCount) As(alias string) *mapInterfaceCount {
	m.mapInterfaceCountDo.DO = *(m.mapInterfaceCountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mapInterfaceCount) updateTableName(table string) *mapInterfaceCount {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MapID = field.NewInt64(table, "map_id")
	m.InterfaceType = field.NewInt32(table, "interface_type")
	m.Day = field.NewTime(table, "day")
	m.Count = field.NewInt32(table, "count")
	m.ErrCount = field.NewInt32(table, "err_count")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *mapInterfaceCount) WithContext(ctx context.Context) IMapInterfaceCountDo {
	return m.mapInterfaceCountDo.WithContext(ctx)
}

func (m mapInterfaceCount) TableName() string { return m.mapInterfaceCountDo.TableName() }

func (m mapInterfaceCount) Alias() string { return m.mapInterfaceCountDo.Alias() }

func (m mapInterfaceCount) Columns(cols ...field.Expr) gen.Columns {
	return m.mapInterfaceCountDo.Columns(cols...)
}

func (m *mapInterfaceCount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mapInterfaceCount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["map_id"] = m.MapID
	m.fieldMap["interface_type"] = m.InterfaceType
	m.fieldMap["day"] = m.Day
	m.fieldMap["count"] = m.Count
	m.fieldMap["err_count"] = m.ErrCount
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m mapInterfaceCount) clone(db *gorm.DB) mapInterfaceCount {
	m.mapInterfaceCountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mapInterfaceCount) replaceDB(db *gorm.DB) mapInterfaceCount {
	m.mapInterfaceCountDo.ReplaceDB(db)
	return m
}

type mapInterfaceCountDo struct{ gen.DO }

type IMapInterfaceCountDo interface {
	gen.SubQuery
	Debug() IMapInterfaceCountDo
	WithContext(ctx context.Context) IMapInterfaceCountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMapInterfaceCountDo
	WriteDB() IMapInterfaceCountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMapInterfaceCountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMapInterfaceCountDo
	Not(conds ...gen.Condition) IMapInterfaceCountDo
	Or(conds ...gen.Condition) IMapInterfaceCountDo
	Select(conds ...field.Expr) IMapInterfaceCountDo
	Where(conds ...gen.Condition) IMapInterfaceCountDo
	Order(conds ...field.Expr) IMapInterfaceCountDo
	Distinct(cols ...field.Expr) IMapInterfaceCountDo
	Omit(cols ...field.Expr) IMapInterfaceCountDo
	Join(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo
	Group(cols ...field.Expr) IMapInterfaceCountDo
	Having(conds ...gen.Condition) IMapInterfaceCountDo
	Limit(limit int) IMapInterfaceCountDo
	Offset(offset int) IMapInterfaceCountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMapInterfaceCountDo
	Unscoped() IMapInterfaceCountDo
	Create(values ...*model.MapInterfaceCount) error
	CreateInBatches(values []*model.MapInterfaceCount, batchSize int) error
	Save(values ...*model.MapInterfaceCount) error
	First() (*model.MapInterfaceCount, error)
	Take() (*model.MapInterfaceCount, error)
	Last() (*model.MapInterfaceCount, error)
	Find() ([]*model.MapInterfaceCount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapInterfaceCount, err error)
	FindInBatches(result *[]*model.MapInterfaceCount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MapInterfaceCount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMapInterfaceCountDo
	Assign(attrs ...field.AssignExpr) IMapInterfaceCountDo
	Joins(fields ...field.RelationField) IMapInterfaceCountDo
	Preload(fields ...field.RelationField) IMapInterfaceCountDo
	FirstOrInit() (*model.MapInterfaceCount, error)
	FirstOrCreate() (*model.MapInterfaceCount, error)
	FindByPage(offset int, limit int) (result []*model.MapInterfaceCount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMapInterfaceCountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mapInterfaceCountDo) Debug() IMapInterfaceCountDo {
	return m.withDO(m.DO.Debug())
}

func (m mapInterfaceCountDo) WithContext(ctx context.Context) IMapInterfaceCountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mapInterfaceCountDo) ReadDB() IMapInterfaceCountDo {
	return m.Clauses(dbresolver.Read)
}

func (m mapInterfaceCountDo) WriteDB() IMapInterfaceCountDo {
	return m.Clauses(dbresolver.Write)
}

func (m mapInterfaceCountDo) Session(config *gorm.Session) IMapInterfaceCountDo {
	return m.withDO(m.DO.Session(config))
}

func (m mapInterfaceCountDo) Clauses(conds ...clause.Expression) IMapInterfaceCountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mapInterfaceCountDo) Returning(value interface{}, columns ...string) IMapInterfaceCountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mapInterfaceCountDo) Not(conds ...gen.Condition) IMapInterfaceCountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mapInterfaceCountDo) Or(conds ...gen.Condition) IMapInterfaceCountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mapInterfaceCountDo) Select(conds ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mapInterfaceCountDo) Where(conds ...gen.Condition) IMapInterfaceCountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mapInterfaceCountDo) Order(conds ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mapInterfaceCountDo) Distinct(cols ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mapInterfaceCountDo) Omit(cols ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mapInterfaceCountDo) Join(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mapInterfaceCountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mapInterfaceCountDo) RightJoin(table schema.Tabler, on ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mapInterfaceCountDo) Group(cols ...field.Expr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mapInterfaceCountDo) Having(conds ...gen.Condition) IMapInterfaceCountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mapInterfaceCountDo) Limit(limit int) IMapInterfaceCountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mapInterfaceCountDo) Offset(offset int) IMapInterfaceCountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mapInterfaceCountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMapInterfaceCountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mapInterfaceCountDo) Unscoped() IMapInterfaceCountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mapInterfaceCountDo) Create(values ...*model.MapInterfaceCount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mapInterfaceCountDo) CreateInBatches(values []*model.MapInterfaceCount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mapInterfaceCountDo) Save(values ...*model.MapInterfaceCount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mapInterfaceCountDo) First() (*model.MapInterfaceCount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterfaceCount), nil
	}
}

func (m mapInterfaceCountDo) Take() (*model.MapInterfaceCount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterfaceCount), nil
	}
}

func (m mapInterfaceCountDo) Last() (*model.MapInterfaceCount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterfaceCount), nil
	}
}

func (m mapInterfaceCountDo) Find() ([]*model.MapInterfaceCount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MapInterfaceCount), err
}

func (m mapInterfaceCountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MapInterfaceCount, err error) {
	buf := make([]*model.MapInterfaceCount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mapInterfaceCountDo) FindInBatches(result *[]*model.MapInterfaceCount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mapInterfaceCountDo) Attrs(attrs ...field.AssignExpr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mapInterfaceCountDo) Assign(attrs ...field.AssignExpr) IMapInterfaceCountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mapInterfaceCountDo) Joins(fields ...field.RelationField) IMapInterfaceCountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mapInterfaceCountDo) Preload(fields ...field.RelationField) IMapInterfaceCountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mapInterfaceCountDo) FirstOrInit() (*model.MapInterfaceCount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterfaceCount), nil
	}
}

func (m mapInterfaceCountDo) FirstOrCreate() (*model.MapInterfaceCount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MapInterfaceCount), nil
	}
}

func (m mapInterfaceCountDo) FindByPage(offset int, limit int) (result []*model.MapInterfaceCount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mapInterfaceCountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mapInterfaceCountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mapInterfaceCountDo) Delete(models ...*model.MapInterfaceCount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mapInterfaceCountDo) withDO(do gen.Dao) *mapInterfaceCountDo {
	m.DO = *do.(*gen.DO)
	return m
}
