// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		UserAccount: newUserAccount(db, opts...),
		UserAuth:    newUserAuth(db, opts...),
		UserSignLog: newUserSignLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	UserAccount userAccount
	UserAuth    userAuth
	UserSignLog userSignLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		UserAccount: q.UserAccount.clone(db),
		UserAuth:    q.UserAuth.clone(db),
		UserSignLog: q.UserSignLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		UserAccount: q.UserAccount.replaceDB(db),
		UserAuth:    q.UserAuth.replaceDB(db),
		UserSignLog: q.UserSignLog.replaceDB(db),
	}
}

type queryCtx struct {
	UserAccount IUserAccountDo
	UserAuth    IUserAuthDo
	UserSignLog IUserSignLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		UserAccount: q.UserAccount.WithContext(ctx),
		UserAuth:    q.UserAuth.WithContext(ctx),
		UserSignLog: q.UserSignLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
