// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGeoPhoneCode = "geo_phone_code"

// GeoPhoneCode mapped from table <geo_phone_code>
type GeoPhoneCode struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;type:character varying(100);not null;uniqueIndex:uniq_geo_phone_cca2,priority:1" json:"name"`
	PhoneCode string         `gorm:"column:phone_code;type:character varying(10);not null;uniqueIndex:uniq_geo_phone_cca2,priority:2" json:"phone_code"`
	MultiLang *string        `gorm:"column:multi_lang;type:jsonb;index:idx_geo_phone_code_multi_lang,priority:1" json:"multi_lang"`
	IsActive  *bool          `gorm:"column:is_active;type:boolean;not null;default:true" json:"is_active"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName GeoPhoneCode's table name
func (*GeoPhoneCode) TableName() string {
	return TableNameGeoPhoneCode
}
