// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGeoRegion = "geo_region"

// GeoRegion mapped from table <geo_region>
type GeoRegion struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CountryCca2 string         `gorm:"column:country_cca2;type:character(2);not null;uniqueIndex:uniq_geo_region_country_code_source,priority:2" json:"country_cca2"`
	Source      int16          `gorm:"column:source;type:smallint;not null;uniqueIndex:uniq_geo_region_country_code_source,priority:3" json:"source"`
	ParentCode  string         `gorm:"column:parent_code;type:character varying(20);not null;index:idx_geo_region_parent_code,priority:1" json:"parent_code"`
	Code        string         `gorm:"column:code;type:character varying(20);not null;uniqueIndex:uniq_geo_region_country_code_source,priority:1" json:"code"`
	Level       int16          `gorm:"column:level;type:smallint;not null" json:"level"`
	MultiLang   *string        `gorm:"column:multi_lang;type:jsonb;index:idx_geo_region_multi_lang,priority:1" json:"multi_lang"`
	IsActive    *bool          `gorm:"column:is_active;type:boolean;not null;default:true" json:"is_active"`
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName GeoRegion's table name
func (*GeoRegion) TableName() string {
	return TableNameGeoRegion
}
