// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGeoCountry = "geo_country"

// GeoCountry mapped from table <geo_country>
type GeoCountry struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Cca2         string         `gorm:"column:cca2;type:character(2);not null;uniqueIndex:uniq_geo_region_country_cca2,priority:1" json:"cca2"`
	Cca3         string         `gorm:"column:cca3;type:character(3);not null;uniqueIndex:uniq_geo_region_country_cca3,priority:1" json:"cca3"`
	Ccn3         string         `gorm:"column:ccn3;type:character(3);not null;uniqueIndex:uniq_geo_region_country_ccn3,priority:1" json:"ccn3"`
	Flag         string         `gorm:"column:flag;type:character varying(20);not null" json:"flag"`
	Continent    string         `gorm:"column:continent;type:character varying(50);not null" json:"continent"`
	SubContinent string         `gorm:"column:sub_continent;type:character varying(50);not null" json:"sub_continent"`
	MultiLang    *string        `gorm:"column:multi_lang;type:jsonb;index:idx_geo_country_multi_lang,priority:1" json:"multi_lang"`
	Independent  bool           `gorm:"column:independent;type:boolean;not null" json:"independent"`
	IsActive     *bool          `gorm:"column:is_active;type:boolean;not null;default:true" json:"is_active"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName GeoCountry's table name
func (*GeoCountry) TableName() string {
	return TableNameGeoCountry
}
