// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/byteflowing/base/dal"
	"github.com/byteflowing/base/gen/config/v1"
	"github.com/byteflowing/base/pkg/captcha"
	"github.com/byteflowing/base/pkg/common"
	"github.com/byteflowing/base/pkg/msg/mail"
	"github.com/byteflowing/base/pkg/msg/sms"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWithConfig(confFile string) *Impl {
	config := NewConfig(confFile)
	user := config.User
	userCache := user.Cache
	redis := config.Redis
	redisRedis := common.NewRDB(redis)
	cache := NewCache(userCache, redisRedis)
	repo := NewRepo(cache)
	db := config.Db
	gormDB := common.NewDb(db)
	query := dal.New(gormDB)
	userJwt := user.Jwt
	userAuthLimiter := user.AuthLimiter
	authLimiter := NewAuthLimiter(userAuthLimiter, redisRedis)
	sessionBlockList := user.SessionBlockList
	blockList := NewSessionBlockList(sessionBlockList, redisRedis)
	jwtService := NewJwtService(userJwt, repo, authLimiter, blockList)
	tokenVerify := user.TwoStepVerifier
	twoStepVerifier := NewTwoStepVerifier(tokenVerify, redisRedis)
	globalId := config.GlobalId
	globalIdGenerator := common.NewGlobalIdGenerator(globalId)
	shortId := config.ShortId
	shortIDGenerator := common.NewShortIDGenerator(globalIdGenerator, shortId)
	configv1Captcha := config.Captcha
	configv1Sms := config.Sms
	smsSms := sms.New(configv1Sms)
	configv1Mail := config.Mail
	mailMail := mail.New(configv1Mail)
	captchaCaptcha := captcha.NewCaptcha(configv1Captcha, redisRedis, smsSms, mailMail)
	wechat := config.Wechat
	wechatManager := common.NewWechatManager(wechat)
	impl := New(user, repo, query, jwtService, twoStepVerifier, shortIDGenerator, globalIdGenerator, captchaCaptcha, wechatManager, authLimiter)
	return impl
}

// wire.go:

var publicSet = wire.NewSet(common.NewDb, common.NewRDB, common.NewDistributedLock, common.NewGlobalIdGenerator, common.NewShortIDGenerator, common.NewWechatManager, captcha.NewSmsCaptcha, captcha.NewMailCaptcha, captcha.NewCaptcha, sms.New, mail.New, dal.New)

var userProviderSet = wire.NewSet(
	NewCache,
	NewRepo,
	NewJwtService,
	NewTwoStepVerifier,
	NewAuthLimiter,
	New,
	NewSessionBlockList,
	NewConfig, wire.FieldsOf(new(*configv1.Config), "Sms", "Mail", "Captcha", "GlobalId", "ShortId", "Wechat", "Db", "Redis", "DistributedLock", "User"), wire.FieldsOf(new(*configv1.User), "AuthLimiter", "Jwt", "TwoStepVerifier", "Cache", "SessionBlockList"),
)
