// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessageSms = "message_sms"

// MessageSms mapped from table <message_sms>
type MessageSms struct {
	ID          int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	MsgType     int16   `gorm:"column:msg_type;type:smallint;not null" json:"msg_type"`
	MsgStatus   int16   `gorm:"column:msg_status;type:smallint;not null;index:idx_msg_status_created_at,priority:2" json:"msg_status"`
	CaptchaType *int16  `gorm:"column:captcha_type;type:smallint" json:"captcha_type"`
	Provider    int32   `gorm:"column:provider;type:integer;not null" json:"provider"`
	Template    string  `gorm:"column:template;type:character varying(20);not null" json:"template"`
	Sign        string  `gorm:"column:sign;type:character varying(20);not null" json:"sign"`
	RequestID   *string `gorm:"column:request_id;type:character varying(50)" json:"request_id"`
	BizID       *string `gorm:"column:biz_id;type:character varying(50);index:idx_biz_id,priority:1" json:"biz_id"`
	Phone       string  `gorm:"column:phone;type:character varying(20);not null;index:idx_phone,priority:1" json:"phone"`
	SenderID    int64   `gorm:"column:sender_id;type:bigint;not null;index:idx_sender_id,priority:1" json:"sender_id"`
	Params      string  `gorm:"column:params;type:character varying(1000);not null" json:"params"`
	Content     *string `gorm:"column:content;type:character varying(1000)" json:"content"`
	ErrCode     *string `gorm:"column:err_code;type:character varying(50)" json:"err_code"`
	ErrMsg      *string `gorm:"column:err_msg;type:text" json:"err_msg"`
	SendDate    *string `gorm:"column:send_date;type:character varying(50)" json:"send_date"`
	ReceiveDate *string `gorm:"column:receive_date;type:character varying(50)" json:"receive_date"`
	DeletedAt   *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	UpdatedAt   int64   `gorm:"column:updated_at;type:bigint;not null" json:"updated_at"`
	CreatedAt   int64   `gorm:"column:created_at;type:bigint;not null;index:idx_msg_status_created_at,priority:1" json:"created_at"`
}

// TableName MessageSms's table name
func (*MessageSms) TableName() string {
	return TableNameMessageSms
}
