// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLoginLog = "user_login_log"

// UserLoginLog mapped from table <user_login_log>
type UserLoginLog struct {
	ID        int64   `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UID       int64   `gorm:"column:uid;type:bigint;not null;index:idx_login_log_uid,priority:1" json:"uid"`
	SessionID string  `gorm:"column:session_id;type:character varying(128);not null;index:idx_login_log_session_id,priority:1" json:"session_id"`
	Type      int16   `gorm:"column:type;type:smallint;not null" json:"type"`
	Status    int16   `gorm:"column:status;type:smallint;not null" json:"status"`
	IP        *string `gorm:"column:ip;type:character varying(128)" json:"ip"`
	Location  *string `gorm:"column:location;type:character varying(100)" json:"location"`
	Agent     *string `gorm:"column:agent;type:character varying(100)" json:"agent"`
	Device    *string `gorm:"column:device;type:character varying(100)" json:"device"`
	DeletedAt *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	UpdatedAt int64   `gorm:"column:updated_at;type:bigint;not null" json:"updated_at"`
	CreatedAt int64   `gorm:"column:created_at;type:bigint;not null" json:"created_at"`
}

// TableName UserLoginLog's table name
func (*UserLoginLog) TableName() string {
	return TableNameUserLoginLog
}
