// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package geo

import (
	"github.com/byteflowing/base/app/geo/service"
	"github.com/byteflowing/base/singleton"
	"github.com/byteflowing/proto/gen/go/config/v1"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewGeoServiceWithConfig(cfg *configv1.Config) *service.GeoService {
	config := cfg.Geo
	dbConfig := cfg.Db
	db := singleton.NewDB(dbConfig)
	redisConfig := cfg.Redis
	redis := singleton.NewRDB(redisConfig)
	localCacheConfig := cfg.LocalCache
	cache := singleton.NewLocalCache(localCacheConfig)
	serviceGeoService := service.NewGeoService(config, db, redis, cache)
	return serviceGeoService
}

// wire.go:

var providerSet = wire.NewSet(singleton.NewDB, singleton.NewRDB, singleton.NewLocalCache, service.NewGeoService, wire.FieldsOf(new(*configv1.Config), "Db", "Redis", "Geo", "LocalCache"))
